import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://platform.xunransports.com/integratedServicesSy');
  await page.getByText('密码登录').click();
  await page.getByRole('textbox', { name: '用户名/手机号' }).click();
  await page.getByRole('textbox', { name: '用户名/手机号' }).fill('xrty');
  await page.getByRole('textbox', { name: '请输入密码' }).click();
  await page.getByRole('textbox', { name: '请输入密码' }).fill('Aa123456');
  await page.getByRole('dialog').getByText('登录', { exact: true }).click();
  await page.getByText('工作台').click();
  await page.getByText('数据管理').click();
  await page.getByText('数据可视化').click();
  await page.getByText('体育测试板块').click();
  await page.getByText('自然排行榜').click();
  await page.getByRole('button', { name: '最强榜 所有项目汇总' }).click();
  await page.getByRole('textbox', { name: '开始日期' }).click();
  await page.getByText('1', { exact: true }).nth(1).click();
  await page.getByText('31', { exact: true }).nth(1).click();
  await page.locator('.ant-select-selection-wrap > .ant-select-selection-search').first().click();
  await page.getByText('自由测试').click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('自由测试').click();
  await page.getByText('打包测试').click();
  await page.locator('.ant-select.ant-cascader > .ant-select-selector > .ant-select-selection-wrap > .ant-select-selection-overflow').click();
  await page.locator('.ant-cascader-checkbox-inner').first().click();
  await page.locator('li:nth-child(2) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.locator('li:nth-child(3) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.locator('li:nth-child(4) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.locator('li:nth-child(5) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.locator('li:nth-child(6) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.locator('#rc_select_28').click();
  await page.getByText('男').click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('男').click();
  await page.getByText('女').click();
  await page.locator('.w-\\[36px\\]').click();
  await page.getByRole('button', { name: '最强榜 所有项目汇总' }).click();
  await page.locator('div').filter({ hasText: /^100米跑$/ }).nth(3).click();
  await page.getByText('800米跑').click();
  await page.getByText('1000米跑').click();
  await page.getByText('米×8往返跑').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByText('导出当前排行榜').click();
  const download = await downloadPromise;
  await page.getByText('赛事排行榜').click();
  await page.getByRole('combobox', { name: '赛项 :' }).click();
  await page.getByText('50米跑', { exact: true }).click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('米跑').click();
  await page.getByText('一分钟跳绳', { exact: true }).click();
  await page.getByRole('tab', { name: '联谊赛' }).click();
  await page.getByText('上海"AI赋能・跳绳比赛（二期）').click();
  await page.getByRole('combobox', { name: '赛项 :' }).click();
  await page.getByText('跳绳项目').click();
  await page.getByText('秒个人竞速赛').click();
  await page.getByRole('combobox', { name: '组别 :' }).click();
  await page.getByText('小学男子组').click();
  await page.locator('#root').getByTitle('小学男子组').click();
  await page.getByText('小学女子组').click();
  await page.locator('.w-\\[36px\\]').click();
  await page.getByRole('tab', { name: '校园赛' }).click();
});
