import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://platform.xunransports.com/integratedServicesSy');
  await page.getByText('密码登录').click();
  await page.getByText('密码登录').click();
  await page.getByRole('textbox', { name: '用户名/手机号' }).click();
  await page.getByRole('textbox', { name: '用户名/手机号' }).fill('xrty');
  await page.getByRole('textbox', { name: '请输入密码' }).click();
  await page.getByRole('textbox', { name: '请输入密码' }).fill('Aa123456');
  await page.getByRole('dialog').getByText('登录', { exact: true }).click();
  await page.getByText('工作台').click();
  await page.getByText('活动管理').click();
  await page.getByText('计划管理').click();
  await page.getByText('第一次测试').first().click();
  await page.getByRole('checkbox', { name: '完成' }).uncheck();
  await page.getByRole('checkbox', { name: '待测' }).uncheck();
  await page.getByText('返回').click();
  await page.getByText('+新建').click();
  await page.getByRole('textbox', { name: '*测试名称：' }).click();
  await page.getByRole('textbox', { name: '*测试名称：' }).fill('测试计划1');
  await page.locator('.ant-select-selection-overflow').click();
  await page.locator('.ant-cascader-checkbox-inner').first().click();
  await page.locator('li:nth-child(2) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.getByRole('combobox', { name: '*评分标准：' }).click();
  await page.getByText('国家学生体质健康标准').click();
  await page.getByRole('textbox', { name: '*起止时间：' }).click();
  await page.getByText('1', { exact: true }).first().click();
  await page.getByText('19').first().click();
  await page.getByRole('radio', { name: '根据评分标准自动生成' }).check();
  await page.getByRole('radio', { name: '无限' }).check();
  await page.getByRole('radio', { name: '最好成绩' }).check();
  await page.getByText('提交').click();
  await page.getByText('返回').click();
  await page.getByText('测试计划1').click();
  await page.getByText('返回').click();
  await page.getByText('第一次测试').first().click();
  await page.getByRole('img').nth(1).click();
  await page.getByText('确认结束').click();
  await page.getByText('返回').click();
});
