import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://platform.xunransports.com/integratedServicesSy');
  await page.getByText('密码登录').click();
  await page.getByRole('textbox', { name: '用户名/手机号' }).click();
  await page.getByRole('textbox', { name: '用户名/手机号' }).fill('xrty');
  await page.getByRole('textbox', { name: '请输入密码' }).click();
  await page.getByRole('textbox', { name: '请输入密码' }).fill('Aa123456');
  await page.getByRole('dialog').getByText('登录', { exact: true }).click();
  await page.getByText('工作台').click();
  await page.getByText('活动管理').click();
  await page.getByText('赛事活动').click();
  await page.getByText('第一次测试', { exact: true }).click();
  await page.getByText('返回').click();
  await page.getByRole('combobox', { name: '赛项 :' }).click();
  await page.getByText('50米跑', { exact: true }).click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('米跑').click();
  await page.getByText('100米跑').click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('米跑').click();
  await page.getByText('800米跑').click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('米跑').click();
  await page.getByText('米×8往返跑').click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('米×8往返跑').click();
  await page.getByText('1000米跑').click();
  await page.locator('[id="__qiankun_microapp_wrapper_for_common__"]').getByTitle('米跑').click();
  await page.getByText('一分钟跳绳', { exact: true }).click();
  await page.getByLabel('close-circle').locator('svg').click();
  await page.getByText('+新建').click();
  await page.getByRole('textbox', { name: '*赛事名称：' }).click();
  await page.getByRole('textbox', { name: '*赛事名称：' }).fill('赛事活动1');
  await page.getByRole('textbox', { name: '*比赛时间：' }).click();
  await page.getByText('1').nth(5).click();
  await page.getByText('19').first().click();
  await page.getByRole('checkbox', { name: '50米跑' }).check();
  await page.getByRole('checkbox', { name: '100米跑' }).check();
  await page.getByRole('checkbox', { name: '800米跑' }).check();
  await page.getByRole('checkbox', { name: '1000米跑' }).check();
  await page.getByRole('checkbox', { name: '米×8往返跑' }).check();
  await page.getByRole('checkbox', { name: '一分钟跳绳' }).check();
  await page.locator('.ant-select-selection-overflow').click();
  await page.locator('.ant-cascader-checkbox-inner').first().click();
  await page.locator('li:nth-child(2) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.getByText('保存').click();
  await page.getByText('编辑').click();
  await page.getByText('二年级 一年级 + 0').click();
  await page.locator('li:nth-child(3) > .ant-cascader-checkbox > .ant-cascader-checkbox-inner').click();
  await page.getByRole('checkbox', { name: '米×8往返跑' }).uncheck();
  await page.getByText('保存').click();
  await page.getByText('返回').click();
  await page.getByText('赛事活动1').click();
  await page.getByText('发布').click();
  await page.getByText('返回').click();
  await page.getByText('评分标准').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('.w-\\[52px\\]').click();
  const download = await downloadPromise;
  await page.getByText('赛事活动').click();
});
